#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("test_cayugasoft.Resource", IsApplication=true)]

namespace test_cayugasoft
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ImageContainerItem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int search = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050024
			public const int AddSomeEntityBtn = 2131034148;
			
			// aapt resource value: 0x7f050012
			public const int BigImageIv = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int BigImageRl = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int BodyEt = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int CloseGalleryItemBtn = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int ContactLl = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ContactName = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int ContactTv = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int ContactsData = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int DeleteGalleryItemBtn = 2131034127;
			
			// aapt resource value: 0x7f050021
			public const int DescriptionEt = 2131034145;
			
			// aapt resource value: 0x7f050009
			public const int DownloadButton = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int DownloadLl = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int EditGalleryItemBtn = 2131034128;
			
			// aapt resource value: 0x7f050026
			public const int EntityLl = 2131034150;
			
			// aapt resource value: 0x7f050020
			public const int EntityNameEt = 2131034144;
			
			// aapt resource value: 0x7f050027
			public const int EntityNameTv = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int EntityUpdatedTv = 2131034152;
			
			// aapt resource value: 0x7f050015
			public const int FlipHorizontalBtn = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int FlipVerticalBtn = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int GalleryBtn = 2131034141;
			
			// aapt resource value: 0x7f05000b
			public const int GalleryLl = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int GalleryRl = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int GallerySv = 2131034122;
			
			// aapt resource value: 0x7f05001f
			public const int ImageContainerBtn = 2131034143;
			
			// aapt resource value: 0x7f050017
			public const int ImageContainerItem = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int ImageContainerLayout = 2131034134;
			
			// aapt resource value: 0x7f050022
			public const int IsActiveCb = 2131034146;
			
			// aapt resource value: 0x7f05001b
			public const int List = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int ListOfContactsBtn = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int ListOfEntitiesBtn = 2131034142;
			
			// aapt resource value: 0x7f05000d
			public const int MenuLl = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int RotateBtn = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int SaveGalleryItemBtn = 2131034126;
			
			// aapt resource value: 0x7f050023
			public const int SaveSomeEntityBtn = 2131034147;
			
			// aapt resource value: 0x7f05001a
			public const int SearchEt = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int SearchIv = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int SearchLayout = 2131034136;
			
			// aapt resource value: 0x7f050004
			public const int SendBtn = 2131034116;
			
			// aapt resource value: 0x7f050025
			public const int SomeEntityList = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int SubjectEt = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Email = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Gallery = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageContainer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListOfContacts = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SomeEntity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SomeEntityList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SomeEntityListItem = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int Gallery = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ImageContainer = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int ListOfContacts = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ListOfEntities = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
